### ISSUE TITLE
Re-use the form

### ISSUE THREAD

**Issue by john-md86** [PeterKassenaar/ng2-form-edit#1]
First of all, thank you for the material! It's the only source I found on the web discussing the use of reactive forms in crud operations.

My question is this: if I need to use the same form (blank) also to add new items, would it change anything? How would it be?

In my case, the form would be as much to add as to edit posts in a blog.

**Comment by PeterKassenaar** [comment]
Hi @jmdmao - sorry for the late reply. I hope it is still useful to you.

I added a second component for adding a new city. It uses the same formdefinition. In order to reuse the form definition, I created a separate file (`shared/model/city.form.model.ts`) that holds the form definition. 

Of course this definition can come from a database as well. Please note you still have to duplicate the HTML for the new component.

If you want to reuse the current component for adding *and* editing a city, I suggest you look in the query string. If there is no parameter, add a new city (don't hit the db). If there is a parameter, fetch the city (as is the case right now).
